# !!!!!!!!!!!!!!!!!!!!!!!!!!!!! Warning: The sample user created in the tutorial will have administrative privileges and is for educational purposes only. !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# kubectl get secret admin-user-kubernetes-dashboard -n kubernetes-dashboard -o jsonpath={".data.token"} | base64 -d
apiVersion: v1
kind: Secret
metadata:
  name: admin-user-kubernetes-dashboard
  namespace: kubernetes-dashboard
  annotations:
    kubernetes.io/service-account.name: "admin-user-kubernetes-dashboard"
type: kubernetes.io/service-account-token
